server:
  port: 80


spring:
  application:
    name: cloud-consumer-payment
  cloud:
    zookeeper:
      connect-string: 192.168.144.132:2181       # 这里连接的是 ZooKeeper 的服务中心
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver             # mysql驱动包 com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 147258369

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl