server:
  port: 9005

spring:
  application:
    name: cloud-provider-payment
  cloud:
    nacos:
      server-addr: localhost:8848

management:
  endpoints:
    web:
      exposure:
        include: "*"