server:
  port: 8005

spring:
  application:
    name: cloud-provider-payment

# ======== cloud ========
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        service-name: ${spring.application.name}

