server:
  port: 8802

eureka:
  instance:
    instance-id: mq-consumer8802
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZoner: http://localhost:7001/eureka, http://localhost:7002/eureka

spring:
  application:
    name: cloud-stream-mq-consumer
  cloud:
    stream:
      binders:
        defaultRabbit:  # binder的名字
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings:
        input:
          destination: studyExchange
          content-type: application/json
          binder: defaultRabbit